/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlocklistEntry {
  'id' : bigint,
  'phone' : string,
  'reason' : string,
}
export interface CallHistory {
  'id' : bigint,
  'wasBlocked' : boolean,
  'callerName' : string,
  'timestamp' : bigint,
  'phone' : string,
  'classification' : string,
}
export interface Contact {
  'id' : bigint,
  'name' : string,
  'trustLevel' : string,
  'phone' : string,
}
export interface _SERVICE {
  'addBlocklistEntry' : ActorMethod<[string, string], bigint>,
  'addCallHistory' : ActorMethod<[string, string, string, boolean], bigint>,
  'addContact' : ActorMethod<[string, string, string], bigint>,
  'deleteContact' : ActorMethod<[bigint], undefined>,
  'getBlocklist' : ActorMethod<[], Array<BlocklistEntry>>,
  'getCallHistory' : ActorMethod<[], Array<CallHistory>>,
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getRecentBlocked' : ActorMethod<[], Array<CallHistory>>,
  'getTotalBlocked' : ActorMethod<[], bigint>,
  'removeBlocklistEntry' : ActorMethod<[bigint], undefined>,
  'updateContact' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];