/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlocklistEntry = IDL.Record({
  'id' : IDL.Nat,
  'phone' : IDL.Text,
  'reason' : IDL.Text,
});
export const CallHistory = IDL.Record({
  'id' : IDL.Nat,
  'wasBlocked' : IDL.Bool,
  'callerName' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'classification' : IDL.Text,
});
export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'trustLevel' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlocklistEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addCallHistory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteContact' : IDL.Func([IDL.Nat], [], []),
  'getBlocklist' : IDL.Func([], [IDL.Vec(BlocklistEntry)], ['query']),
  'getCallHistory' : IDL.Func([], [IDL.Vec(CallHistory)], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getRecentBlocked' : IDL.Func([], [IDL.Vec(CallHistory)], ['query']),
  'getTotalBlocked' : IDL.Func([], [IDL.Nat], ['query']),
  'removeBlocklistEntry' : IDL.Func([IDL.Nat], [], []),
  'updateContact' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlocklistEntry = IDL.Record({
    'id' : IDL.Nat,
    'phone' : IDL.Text,
    'reason' : IDL.Text,
  });
  const CallHistory = IDL.Record({
    'id' : IDL.Nat,
    'wasBlocked' : IDL.Bool,
    'callerName' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'classification' : IDL.Text,
  });
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'trustLevel' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlocklistEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addCallHistory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteContact' : IDL.Func([IDL.Nat], [], []),
    'getBlocklist' : IDL.Func([], [IDL.Vec(BlocklistEntry)], ['query']),
    'getCallHistory' : IDL.Func([], [IDL.Vec(CallHistory)], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getRecentBlocked' : IDL.Func([], [IDL.Vec(CallHistory)], ['query']),
    'getTotalBlocked' : IDL.Func([], [IDL.Nat], ['query']),
    'removeBlocklistEntry' : IDL.Func([IDL.Nat], [], []),
    'updateContact' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };